package com.xlx.springbootmybatis.model;

import java.util.Date;

public class Log {

    public Log() {
    }

    public Log(String action) {
        this.action = action;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.action
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user
     *
     * @return the value of log.user
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user
     *
     * @param user the value for log.user
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.action
     *
     * @return the value of log.action
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.action
     *
     * @param action the value for log.action
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbg.generated Tue Jul 31 08:49:05 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}